export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_GYM_CLASSES = 'SET_GYM_CLASSES';
export const ADD_GYM_CLASS = 'ADD_GYM_CLASS';
export const GYM_CLASS_FETCHED = 'GYM_CLASS_FETCHED';
export const GYM_CLASS_UPDATED = 'GYM_CLASS_UPDATED';
